services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #     # - ./server/mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo-data: